# Generated by Django 5.0.1 on 2024-01-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIP_status_name', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vipStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.vipstatus'),
        ),
    ]
